-- MORDECAI_EA SCANNER database schema
-- SQLite. No MT5 master password is ever stored here.

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at INTEGER NOT NULL
);

-- One row per paired MT5 terminal. device_token is what the EA sends;
-- it is a random pairing token generated by this app, NOT the MT5 password.
CREATE TABLE IF NOT EXISTS mt5_connections (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  device_token TEXT UNIQUE NOT NULL,
  account_number INTEGER,
  broker TEXT,
  server TEXT,
  currency TEXT,
  status TEXT NOT NULL DEFAULT 'disconnected', -- connected | connecting | disconnected
  last_sync_at INTEGER,
  last_deal_id INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS account_snapshots (
  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL REFERENCES mt5_connections(id),
  balance REAL,
  equity REAL,
  margin REAL,
  free_margin REAL,
  margin_level REAL,
  open_positions_json TEXT,
  taken_at INTEGER NOT NULL
);

-- Closed trades, deduped by MT5 deal_id
CREATE TABLE IF NOT EXISTS trade_history (
  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL REFERENCES mt5_connections(id),
  deal_id INTEGER NOT NULL,
  order_id INTEGER,
  symbol TEXT,
  direction TEXT,
  volume REAL,
  price REAL,
  profit REAL,
  commission REAL,
  swap REAL,
  closed_at INTEGER,
  UNIQUE(connection_id, deal_id)
);

-- AI-generated signals (never auto-executed)
CREATE TABLE IF NOT EXISTS signals (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  setup_id TEXT UNIQUE NOT NULL, -- e.g. US30-SELL-2026-08-16-001
  symbol TEXT NOT NULL,
  direction TEXT NOT NULL, -- buy | sell | no_trade
  verdict TEXT, -- NO TRADE | WEAK SETUP | VALID SETUP | STRONG SIGNAL | HIGH-CONFLUENCE SIGNAL
  confidence INTEGER,
  entry_low REAL,
  entry_high REAL,
  stop_loss REAL,
  tp1 REAL,
  tp2 REAL,
  tp3 REAL,
  risk_reward REAL,
  reasoning_json TEXT, -- structured "why this signal exists" checklist
  status TEXT NOT NULL DEFAULT 'DETECTED', -- DETECTED|CONFIRMED|ACTIVE|TP1|TP2|TP3|INVALIDATED
  source TEXT NOT NULL, -- 'screenshot' | 'live_data'
  created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_signals_user ON signals(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trade_history_conn ON trade_history(connection_id, closed_at DESC);
